name: Node.js CI and Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create and commit file
        run: |
          echo "This is a sample file created by GitHub Actions" > sample-file.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add sample-file.txt
          git commit -m "Add sample file"
          git push
