name: Commit Test

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create report file
        run: |
          timestamp=$(date +"%Y%m%d-%H%M")
          echo $timestamp > "report-${timestamp}.txt"
      - name: Commit report
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -am "WORKING: Automated report"
          git push
#      - name: Create and commit file
#        run: |
#          echo "This is a sample file created by GitHub Actions" > sample-file.txt
#          git add sample-file.txt
#          git commit -m "WORKING: Add sample file"
#          git push
